-- ============================================================================
--  myRPS — COMPLETE DATABASE SETUP
--
--  HOW TO USE THIS FILE
--
--  1. Open your project at https://supabase.com/dashboard
--  2. Click "SQL Editor" in the left sidebar
--  3. Click "New query"
--  4. Copy EVERYTHING in this file and paste it in
--  5. Click "Run"  (or press Ctrl+Enter)
--
--  It takes a few seconds. When it finishes you should see
--  "Success. No rows returned" — that is what success looks like.
--
--  Running it a second time is harmless. It will not delete student data.
--
--  Generated from the files in supabase/. Do not edit this file by hand —
--  edit the numbered file and run "npm run db:bundle".
-- ============================================================================


-- ===== 01_schema.sql =================================================

-- =====================================================================
-- myRPS — 01_schema.sql
-- Run this FIRST in Supabase → SQL Editor → New query.
-- Creates every table. No data, no permissions yet.
-- =====================================================================

create extension if not exists "pgcrypto";

-- ---------- enumerated types -------------------------------------------------
do $$ begin
  create type approval_state as enum ('pending', 'approved', 'rejected');
exception when duplicate_object then null; end $$;

do $$ begin
  -- Which block of the curriculum a course belongs to (UR6523007 structure).
  create type subject_category as enum (
    'core',          -- Discipline Core
    'elective',      -- Discipline Elective
    'common_core',   -- Common Core (IMQ maths/statistics)
    'university',    -- University Requirement (SMB/SMU)
    'cocurriculum',  -- SMZ co-curriculum
    'audit'          -- Audit only, no credit (e.g. SMB10102)
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type record_state as enum ('planned', 'active', 'pass', 'fail', 'exempted');
exception when duplicate_object then null; end $$;

-- ---------- who is an admin --------------------------------------------------
-- Deliberately its own table. Role must never live on a row the student can
-- write, and never in auth.users.raw_user_meta_data (which any logged-in user
-- can rewrite with supabase.auth.updateUser).
create table if not exists public.admins (
  user_id    uuid primary key references auth.users (id) on delete cascade,
  added_at   timestamptz not null default now(),
  note       text
);

-- ---------- settings the RPS can change without a redeploy -------------------
create table if not exists public.app_settings (
  key         text primary key,
  value       text,
  updated_at  timestamptz not null default now()
);

-- ---------- student profile (AMIS-style, minus the financial fields) ---------
create table if not exists public.profiles (
  id                  uuid primary key references auth.users (id) on delete cascade,
  approval_state      approval_state not null default 'pending',
  approved_at         timestamptz,
  approved_by         uuid references auth.users (id),
  rejection_reason    text,

  -- Personal details
  full_name           text,
  matric_no           text unique,
  ic_no               text,
  date_of_birth       date,
  birth_state         text,
  gender              text,
  disability          text,
  race                text,
  religion            text,
  nationality         text default 'Warganegara Malaysia',
  marital_status      text,
  parental_income     text,

  -- Contact
  email_personal      text,
  email_official      text,
  phone_home          text,
  phone_mobile        text,

  -- Address
  address_line        text,
  postcode            text,
  city                text,
  state               text,
  hostel_status       text,

  -- Next of kin & parents
  kin_name            text,
  kin_relation        text,
  kin_phone           text,
  father_occupation   text,
  mother_occupation   text,
  dependents_count    int,
  parent_address      text,

  -- Academic
  programme_code      text default 'UR6523007',
  intake_year         text,                 -- '2022', '2025' … selects the curriculum version
  intake_semester     text,                 -- e.g. '2022-S1'
  entry_type          text,
  programme_mode      text default 'Full Time',
  spm_results         jsonb default '{}'::jsonb,
  stpm_results        jsonb default '{}'::jsonb,
  muet_band           text,

  -- Sponsor (name only — no bank account, no bank code, by design)
  sponsor_name        text,

  career_goal         text,
  avatar_path         text,                 -- storage object path, NOT a public URL

  -- PDPA
  consent_version     text,
  consent_at          timestamptz,

  profile_completed   boolean not null default false,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

comment on table public.profiles is
  'Student-declared data. Not an official record — AMIS remains the source of truth.';

-- ---------- grade scale (editable; seeded from the RPS Panduan) --------------
create table if not exists public.grade_scale (
  grade       text primary key,
  points      numeric(4,2) not null,
  is_pass     boolean not null default true,
  sort_order  int not null
);

-- ---------- master curriculum ------------------------------------------------
create table if not exists public.curriculum_subjects (
  id                uuid primary key default gen_random_uuid(),
  programme_code    text not null default 'UR6523007',
  intake_year       text not null,             -- curriculum version, e.g. '2025'
  code              text not null,
  name_en           text not null,
  name_ms           text,
  credit            int  not null check (credit >= 0),
  category          subject_category not null,
  planned_semester  int check (planned_semester between 1 and 8),
  -- Industrial Training is graded Pass/Fail, not A–F.
  is_graded         boolean not null default true,
  -- Audit courses carry no credit toward the 140.
  counts_to_total   boolean not null default true,
  is_active         boolean not null default true,
  created_at        timestamptz not null default now(),
  unique (programme_code, intake_year, code)
);

-- ---------- what each student has actually taken -----------------------------
create table if not exists public.student_records (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references public.profiles (id) on delete cascade,
  subject_id     uuid not null references public.curriculum_subjects (id) on delete cascade,
  attempt_no     int  not null default 1 check (attempt_no between 1 and 6),
  state          record_state not null default 'planned',
  grade          text references public.grade_scale (grade),
  semester_taken text check (semester_taken ~ '^\d{4}-(S1|S2|T)$'),  -- 2024-S1 / 2024-T
  updated_at     timestamptz not null default now(),
  created_at     timestamptz not null default now(),
  -- One row per attempt. Without this a student can add the same subject
  -- five times and show 180/140.
  unique (user_id, subject_id, attempt_no)
);

create index if not exists student_records_user_idx on public.student_records (user_id);

-- ---------- Modul 03: Borang Sasaran (target grade planner) ------------------
create table if not exists public.academic_targets (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references public.profiles (id) on delete cascade,
  subject_id     uuid not null references public.curriculum_subjects (id) on delete cascade,
  target_grade   text not null references public.grade_scale (grade),
  semester_label text check (semester_label ~ '^\d{4}-(S1|S2|T)$'),
  created_at     timestamptz not null default now(),
  unique (user_id, subject_id)
);

-- ---------- psychometric (Lampiran 1, businessballs MI test) -----------------
create table if not exists public.psychometric_attempts (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles (id) on delete cascade,
  attempt_no  int not null default 1,
  -- {"1": 3, "2": 1, ... "70": 4} — kept so an attempt can be re-scored later
  responses   jsonb not null,
  linguistic    int not null,
  logical       int not null,
  musical       int not null,
  kinesthetic   int not null,
  spatial       int not null,
  interpersonal int not null,
  intrapersonal int not null,
  strength      text not null,
  weakness      text not null,
  taken_at    timestamptz not null default now(),
  unique (user_id, attempt_no)
);

-- Lampiran 3: what the student will do about their weakness
create table if not exists public.action_plans (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles (id) on delete cascade,
  weakness    text not null,
  action      text not null,
  created_at  timestamptz not null default now()
);

-- ---------- Borang 1: meeting log -------------------------------------------
create table if not exists public.meetings (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references public.profiles (id) on delete cascade,
  meeting_at    timestamptz not null,
  location      text not null,
  topic         text not null,
  student_notes text,
  rps_notes     text,                       -- only the admin may write/read this
  -- The leaderboard ranks on meetings, so meetings must be confirmable.
  verified      boolean not null default false,
  verified_at   timestamptz,
  created_by    uuid not null references auth.users (id),
  created_at    timestamptz not null default now()
);

create index if not exists meetings_user_idx on public.meetings (user_id, meeting_at desc);

-- ---------- 7 Pillars --------------------------------------------------------
create table if not exists public.pillar_completions (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references public.profiles (id) on delete cascade,
  pillar_code   text not null check (pillar_code in ('p1','p2','p3','p4','p5','p6','p7')),
  activity_name text,
  completed_on  date,
  verified      boolean not null default false,
  created_at    timestamptz not null default now(),
  unique (user_id, pillar_code)
);

-- ---------- chatroom ---------------------------------------------------------
create table if not exists public.chat_messages (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles (id) on delete cascade,
  body        text not null check (char_length(body) between 1 and 1000),
  is_announcement boolean not null default false,
  deleted_at  timestamptz,
  deleted_by  uuid references auth.users (id),
  created_at  timestamptz not null default now()
);

create index if not exists chat_created_idx on public.chat_messages (created_at desc);

-- ---------- audit trail ------------------------------------------------------
create table if not exists public.audit_log (
  id           bigserial primary key,
  actor_id     uuid references auth.users (id),
  action       text not null,
  target_user  uuid references auth.users (id),
  detail       jsonb default '{}'::jsonb,
  created_at   timestamptz not null default now()
);

-- ---------- how many credits each block requires -----------------------------
-- Needed because the elective *options* are all seeded as rows (9 of them) but
-- a student only takes 2. Summing the subject table would overcount, so the
-- requirement is stated explicitly per category.
create table if not exists public.curriculum_requirements (
  programme_code    text not null default 'UR6523007',
  intake_year       text not null,
  category          subject_category not null,
  required_credits  int not null check (required_credits >= 0),
  primary key (programme_code, intake_year, category)
);

-- ---------- psychometric question bank ---------------------------------------
-- The 70 statements live in the database, not in the repo. The instrument is
-- Chislett & Chapman's Multiple Intelligences Test (businessballs.com), free to
-- use but licensed "not to be sold or published" — so a public GitHub repo is
-- the wrong place for it. Seed it with the separate psychometric_items.sql.
create table if not exists public.psychometric_items (
  question_no  int primary key check (question_no between 1 and 200),
  intelligence text not null check (intelligence in
    ('linguistic','logical','musical','kinesthetic','spatial','interpersonal','intrapersonal')),
  text_en      text not null,
  text_ms      text,
  is_active    boolean not null default true
);


-- ===== 02_functions.sql ==============================================

-- =====================================================================
-- myRPS — 02_functions.sql   (run SECOND)
-- Helper functions, signup gate, and the admin-only actions.
-- =====================================================================

-- ---------- helpers ----------------------------------------------------------
-- security definer so a student can ask "am I an admin?" without being able to
-- read the admins table itself. search_path is pinned — without that, a
-- malicious search_path can hijack the function body.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (select 1 from public.admins a where a.user_id = auth.uid());
$$;

create or replace function public.is_approved()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.approval_state = 'approved'
  );
$$;

-- ---------- keep updated_at honest -------------------------------------------
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_touch on public.profiles;
create trigger profiles_touch before update on public.profiles
  for each row execute function public.touch_updated_at();

drop trigger if exists records_touch on public.student_records;
create trigger records_touch before update on public.student_records
  for each row execute function public.touch_updated_at();

-- ---------- signup gate ------------------------------------------------------
-- Fires when Supabase Auth creates a user. Two jobs:
--   1. reject any address outside the allowed domain,
--   2. create the pending profile row.
-- The frontend checks the domain too, but only this check is enforceable.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  allowed text;
  bootstrap text;
begin
  select value into allowed from public.app_settings where key = 'allowed_email_domain';
  select value into bootstrap from public.app_settings where key = 'bootstrap_admin_email';

  -- allowed_email_domain may hold several domains separated by commas, e.g.
  -- 'studentmail.unimap.edu.my,unimap.edu.my' so staff can register too.
  if allowed is not null and allowed <> ''
     and not exists (
       select 1
       from unnest(string_to_array(allowed, ',')) as d
       where lower(new.email) like '%@' || lower(btrim(d))
     )
     and lower(new.email) <> lower(coalesce(bootstrap, '')) then
    raise exception 'Registration is limited to these domains: %', allowed
      using errcode = 'check_violation';
  end if;

  insert into public.profiles (id, email_official, approval_state)
  values (
    new.id,
    new.email,
    (case
       when lower(new.email) = lower(coalesce(bootstrap, '')) then 'approved'
       else 'pending'
     end)::public.approval_state
  )
  on conflict (id) do nothing;

  -- The very first account, if it matches bootstrap_admin_email, becomes the RPS.
  if bootstrap is not null and lower(new.email) = lower(bootstrap) then
    insert into public.admins (user_id, note) values (new.id, 'bootstrap admin')
    on conflict (user_id) do nothing;
  end if;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------- students must not be able to approve themselves ------------------
create or replace function public.guard_profile_columns()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  -- auth.uid() is null when there is no logged-in user: the Supabase SQL
  -- Editor, the Table Editor, and anything using the service role. Those are
  -- already fully trusted, and the RPS must be able to repair an account by
  -- hand -- for example after registering before bootstrap_admin_email was
  -- set. Without this, the fix silently does nothing.
  if auth.uid() is null or public.is_admin() then
    return new;
  end if;
  -- Silently pin the privileged columns back to their stored values rather than
  -- erroring, so an ordinary profile save still succeeds.
  new.approval_state   := old.approval_state;
  new.approved_at      := old.approved_at;
  new.approved_by      := old.approved_by;
  new.rejection_reason := old.rejection_reason;
  return new;
end;
$$;

drop trigger if exists profiles_guard on public.profiles;
create trigger profiles_guard before update on public.profiles
  for each row execute function public.guard_profile_columns();

-- ---------- admin actions (the only way approval state changes) --------------
create or replace function public.admin_set_approval(
  target uuid,
  new_state approval_state,
  reason text default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.is_admin() then
    raise exception 'Admin only.' using errcode = 'insufficient_privilege';
  end if;

  update public.profiles
     set approval_state   = new_state,
         approved_at      = case when new_state = 'approved' then now() else null end,
         approved_by      = case when new_state = 'approved' then auth.uid() else null end,
         rejection_reason = reason
   where id = target;

  insert into public.audit_log (actor_id, action, target_user, detail)
  values (auth.uid(), 'set_approval', target, jsonb_build_object('state', new_state, 'reason', reason));
end;
$$;

-- Clears the one-attempt lock so the student can retake the psychometric test.
-- History is kept; the next attempt gets the next attempt_no.
create or replace function public.admin_reset_psychometric(target uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.is_admin() then
    raise exception 'Admin only.' using errcode = 'insufficient_privilege';
  end if;

  insert into public.audit_log (actor_id, action, target_user, detail)
  values (auth.uid(), 'reset_psychometric', target,
          jsonb_build_object('attempts_before',
            (select count(*) from public.psychometric_attempts where user_id = target)));
end;
$$;

-- True when the student may start a test: never taken one, or the RPS has
-- reset them since their last attempt.
create or replace function public.can_take_psychometric()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  with last_attempt as (
    select max(a.taken_at) as at
    from public.psychometric_attempts a
    where a.user_id = auth.uid()
  ),
  last_reset as (
    select max(l.created_at) as at
    from public.audit_log l
    where l.target_user = auth.uid() and l.action = 'reset_psychometric'
  )
  select case
    -- never taken it
    when (select at from last_attempt) is null then true
    -- taken it: only a reset that came AFTER the last attempt reopens it.
    -- coalesce defaults to FALSE here on purpose. Defaulting to true would
    -- mean "no reset recorded" reads as "go ahead", which is the opposite of
    -- what a one-attempt lock is for.
    else coalesce((select at from last_reset) > (select at from last_attempt), false)
  end;
$$;

create or replace function public.admin_verify_meeting(meeting_id uuid, value boolean)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.is_admin() then
    raise exception 'Admin only.' using errcode = 'insufficient_privilege';
  end if;
  update public.meetings
     set verified = value, verified_at = case when value then now() else null end
   where id = meeting_id;
end;
$$;

-- Lets a student erase their own account and everything attached to it (PDPA).
create or replace function public.delete_my_account()
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if auth.uid() is null then
    raise exception 'Not signed in.';
  end if;
  insert into public.audit_log (actor_id, action, target_user, detail)
  values (auth.uid(), 'self_delete', auth.uid(), '{}'::jsonb);
  -- cascades through every table that references profiles / auth.users
  delete from auth.users where id = auth.uid();
end;
$$;

revoke all on function public.admin_set_approval(uuid, approval_state, text) from anon;
revoke all on function public.admin_reset_psychometric(uuid) from anon;
revoke all on function public.admin_verify_meeting(uuid, boolean) from anon;
revoke all on function public.delete_my_account() from anon;


-- ===== 03_rls.sql ====================================================

-- =====================================================================
-- myRPS — 03_rls.sql   (run THIRD)
--
-- READ THIS FIRST. The site is a static page on GitHub Pages, so the anon
-- key is inside the JavaScript bundle and anyone can read it. That is normal
-- and safe ONLY because of the policies below: they are the whole security
-- model. Anything not protected here is public to anyone who opens devtools.
-- =====================================================================

alter table public.admins              enable row level security;
alter table public.app_settings        enable row level security;
alter table public.profiles            enable row level security;
alter table public.grade_scale         enable row level security;
alter table public.curriculum_subjects enable row level security;
alter table public.curriculum_requirements enable row level security;
alter table public.student_records     enable row level security;
alter table public.academic_targets    enable row level security;
alter table public.psychometric_attempts enable row level security;
alter table public.action_plans        enable row level security;
alter table public.meetings            enable row level security;
alter table public.pillar_completions  enable row level security;
alter table public.chat_messages       enable row level security;
alter table public.audit_log           enable row level security;

-- ---------- admins: readable by nobody, writable by nobody -------------------
-- Membership is managed in the Supabase dashboard only. is_admin() reads it
-- with security definer, so no policy is needed for the app to work.
drop policy if exists admins_select on public.admins;
create policy admins_select on public.admins for select
  using (public.is_admin());

-- ---------- settings ---------------------------------------------------------
drop policy if exists settings_read on public.app_settings;
create policy settings_read on public.app_settings for select
  to authenticated using (true);

drop policy if exists settings_write on public.app_settings;
create policy settings_write on public.app_settings for all
  to authenticated using (public.is_admin()) with check (public.is_admin());

-- ---------- profiles: your own row, or everything if you are the RPS ---------
drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own on public.profiles for select
  to authenticated using (id = auth.uid() or public.is_admin());

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles for update
  to authenticated using (id = auth.uid() or public.is_admin())
  with check (id = auth.uid() or public.is_admin());

-- INSERT is handled by the handle_new_user trigger; students never insert.
drop policy if exists profiles_delete_admin on public.profiles;
create policy profiles_delete_admin on public.profiles for delete
  to authenticated using (public.is_admin());

-- ---------- reference data: readable by any signed-in user ------------------
drop policy if exists grades_read on public.grade_scale;
create policy grades_read on public.grade_scale for select
  to authenticated using (true);

drop policy if exists grades_write on public.grade_scale;
create policy grades_write on public.grade_scale for all
  to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists subjects_read on public.curriculum_subjects;
create policy subjects_read on public.curriculum_subjects for select
  to authenticated using (true);

drop policy if exists subjects_write on public.curriculum_subjects;
create policy subjects_write on public.curriculum_subjects for all
  to authenticated using (public.is_admin()) with check (public.is_admin());

-- Credit requirements drive every progress bar in the app. Readable by all,
-- writable only by the RPS — otherwise a student could set their own
-- graduation target to 6 credits.
drop policy if exists requirements_read on public.curriculum_requirements;
create policy requirements_read on public.curriculum_requirements for select
  to authenticated using (true);

drop policy if exists requirements_write on public.curriculum_requirements;
create policy requirements_write on public.curriculum_requirements for all
  to authenticated using (public.is_admin()) with check (public.is_admin());

-- ---------- academic records: private to the student and the RPS ------------
drop policy if exists records_rw on public.student_records;
create policy records_rw on public.student_records for all
  to authenticated
  using (user_id = auth.uid() or public.is_admin())
  with check ((user_id = auth.uid() and public.is_approved()) or public.is_admin());

drop policy if exists targets_rw on public.academic_targets;
create policy targets_rw on public.academic_targets for all
  to authenticated
  using (user_id = auth.uid() or public.is_admin())
  with check ((user_id = auth.uid() and public.is_approved()) or public.is_admin());

-- ---------- psychometric: insert-only for students, never editable ----------
drop policy if exists psych_select on public.psychometric_attempts;
create policy psych_select on public.psychometric_attempts for select
  to authenticated using (user_id = auth.uid() or public.is_admin());

drop policy if exists psych_insert on public.psychometric_attempts;
create policy psych_insert on public.psychometric_attempts for insert
  to authenticated
  with check (
    user_id = auth.uid()
    and public.is_approved()
    and public.can_take_psychometric()      -- the one-attempt lock, enforced here
  );
-- No UPDATE and no DELETE policy: a submitted attempt is immutable. Only the
-- RPS can unlock a retake, via admin_reset_psychometric().

drop policy if exists plans_rw on public.action_plans;
create policy plans_rw on public.action_plans for all
  to authenticated
  using (user_id = auth.uid() or public.is_admin())
  with check ((user_id = auth.uid() and public.is_approved()) or public.is_admin());

-- ---------- meetings ---------------------------------------------------------
drop policy if exists meetings_select on public.meetings;
create policy meetings_select on public.meetings for select
  to authenticated using (user_id = auth.uid() or public.is_admin());

drop policy if exists meetings_insert on public.meetings;
create policy meetings_insert on public.meetings for insert
  to authenticated
  with check (
    ((user_id = auth.uid() and public.is_approved()) or public.is_admin())
    and created_by = auth.uid()
  );

drop policy if exists meetings_update on public.meetings;
create policy meetings_update on public.meetings for update
  to authenticated
  using ((user_id = auth.uid() and not verified) or public.is_admin())
  with check ((user_id = auth.uid() and not verified) or public.is_admin());
-- A student may correct a meeting until the RPS verifies it, then it is frozen.

drop policy if exists meetings_delete on public.meetings;
create policy meetings_delete on public.meetings for delete
  to authenticated using ((user_id = auth.uid() and not verified) or public.is_admin());

-- ---------- pillars ----------------------------------------------------------
drop policy if exists pillars_rw on public.pillar_completions;
create policy pillars_rw on public.pillar_completions for all
  to authenticated
  using (user_id = auth.uid() or public.is_admin())
  with check ((user_id = auth.uid() and public.is_approved()) or public.is_admin());

-- ---------- chat: approved students only ------------------------------------
drop policy if exists chat_select on public.chat_messages;
create policy chat_select on public.chat_messages for select
  to authenticated using (public.is_approved() or public.is_admin());

drop policy if exists chat_insert on public.chat_messages;
create policy chat_insert on public.chat_messages for insert
  to authenticated
  with check (
    user_id = auth.uid()
    and (public.is_approved() or public.is_admin())
    and (not is_announcement or public.is_admin())   -- only the RPS may broadcast
  );

drop policy if exists chat_update on public.chat_messages;
create policy chat_update on public.chat_messages for update
  to authenticated
  using (user_id = auth.uid() or public.is_admin())
  with check (user_id = auth.uid() or public.is_admin());
-- Deletion is a soft delete (set deleted_at) so the RPS keeps a moderation trail.

drop policy if exists chat_delete on public.chat_messages;
create policy chat_delete on public.chat_messages for delete
  to authenticated using (public.is_admin());

-- ---------- audit log: admin reads, nobody writes directly ------------------
drop policy if exists audit_select on public.audit_log;
create policy audit_select on public.audit_log for select
  to authenticated using (public.is_admin());
-- Writes happen inside security-definer functions, which bypass RLS.

-- ---------- psychometric question bank --------------------------------------
alter table public.psychometric_items enable row level security;

drop policy if exists items_read on public.psychometric_items;
create policy items_read on public.psychometric_items for select
  to authenticated using (public.is_approved() or public.is_admin());
-- Signed-in and approved only. Not readable by anon, so the instrument is not
-- served to the open internet.

drop policy if exists items_write on public.psychometric_items;
create policy items_write on public.psychometric_items for all
  to authenticated using (public.is_admin()) with check (public.is_admin());

-- ---------- table privileges -------------------------------------------------
-- Supabase grants new public tables to anon and authenticated automatically via
-- default privileges. Rather than depend on that, state it explicitly and drop
-- anon entirely: nothing in myRPS is meant to be readable while signed out, so
-- the logged-out role should not hold a grant on any of it. RLS is still the
-- rule that decides WHICH rows a signed-in user sees; this decides who may
-- reach the tables at all.
do $$
declare t record;
begin
  for t in
    select tablename from pg_tables where schemaname = 'public'
  loop
    execute format('revoke all on public.%I from anon', t.tablename);
    execute format('grant select, insert, update, delete on public.%I to authenticated', t.tablename);
  end loop;
end $$;

grant usage on schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on all functions in schema public to authenticated;

-- Future tables added by the RPS through the dashboard inherit the same shape.
alter default privileges in schema public
  grant select, insert, update, delete on tables to authenticated;
alter default privileges in schema public
  revoke all on tables from anon;


-- ===== 04_views.sql ==================================================

-- =====================================================================
-- myRPS — 04_views.sql   (run FOURTH)
-- Derived numbers: credits, indicative GPA, the safe leaderboard.
-- =====================================================================

-- One row per subject a student has cleared, using their best (latest) attempt.
-- Without the distinct-on, a subject taken three times would be counted three
-- times and a student could show 180 / 140 credits.
create or replace view public.v_cleared_subjects
with (security_invoker = on) as
select distinct on (r.user_id, r.subject_id)
  r.user_id,
  r.subject_id,
  s.credit,
  s.category,
  s.counts_to_total
from public.student_records r
join public.curriculum_subjects s on s.id = r.subject_id
where r.state in ('pass', 'exempted')
order by r.user_id, r.subject_id, r.attempt_no desc;

-- Latest graded attempt per subject. This is the CGPA rule from the RPS
-- Panduan: when a course has been repeated, the failed attempt drops out of
-- both the numerator and the denominator.
create or replace view public.v_gpa_attempts
with (security_invoker = on) as
select distinct on (r.user_id, r.subject_id)
  r.user_id,
  r.subject_id,
  r.semester_taken,
  s.credit,
  g.points
from public.student_records r
join public.curriculum_subjects s on s.id = r.subject_id
join public.grade_scale g on g.grade = r.grade
where s.is_graded
  and r.grade is not null
  and r.state in ('pass', 'fail')
order by r.user_id, r.subject_id, r.attempt_no desc;

-- Indicative CGPA. Indicative, not official — it is computed from what the
-- student typed in, and AMIS remains the source of truth.
create or replace view public.v_student_cgpa
with (security_invoker = on) as
select
  user_id,
  round(sum(points * credit) / nullif(sum(credit), 0), 2) as cgpa,
  sum(credit) as graded_credits
from public.v_gpa_attempts
group by user_id;

-- Semester-by-semester GPA, for the trend chart and the improvement badge.
create or replace view public.v_semester_gpa
with (security_invoker = on) as
select
  user_id,
  semester_taken,
  round(sum(points * credit) / nullif(sum(credit), 0), 2) as gpa,
  sum(credit) as credits
from public.v_gpa_attempts
where semester_taken is not null
group by user_id, semester_taken;

-- Credits passed per semester — the input to the Continuous Improvement badge.
create or replace view public.v_semester_passes
with (security_invoker = on) as
select
  r.user_id,
  r.semester_taken,
  count(*) filter (where r.state = 'pass') as passed_subjects
from public.student_records r
where r.semester_taken is not null
group by r.user_id, r.semester_taken;

-- The RPS master list. security_invoker = on means a student querying this
-- sees only their own row; the RPS sees everyone.
create or replace view public.student_summary
with (security_invoker = on) as
select
  p.id                              as user_id,
  p.full_name,
  p.matric_no,
  p.approval_state,
  p.programme_code,
  p.intake_year,
  p.profile_completed,
  p.career_goal,
  coalesce(c.earned, 0)             as credits_earned,
  coalesce(req.required, 140)       as credits_required,
  g.cgpa,
  coalesce(pil.done, 0)             as pillars_done,
  coalesce(m.total, 0)              as meetings_total,
  coalesce(m.verified, 0)           as meetings_verified,
  m.last_meeting_at,
  coalesce(f.open_fails, 0)         as open_fails,
  exists (select 1 from public.psychometric_attempts a where a.user_id = p.id) as has_psychometric
from public.profiles p
left join (
  select user_id, sum(credit) as earned
  from public.v_cleared_subjects where counts_to_total group by user_id
) c on c.user_id = p.id
left join lateral (
  select sum(cr.required_credits) as required
  from public.curriculum_requirements cr
  where cr.programme_code = p.programme_code
    and cr.intake_year = p.intake_year
) req on true
left join public.v_student_cgpa g on g.user_id = p.id
left join (
  select user_id, count(*) as done from public.pillar_completions group by user_id
) pil on pil.user_id = p.id
left join (
  select user_id,
         count(*) as total,
         count(*) filter (where verified) as verified,
         max(meeting_at) as last_meeting_at
  from public.meetings group by user_id
) m on m.user_id = p.id
left join (
  -- a fail with no later passing attempt of the same subject
  select r.user_id, count(*) as open_fails
  from public.student_records r
  where r.state = 'fail'
    and not exists (
      select 1 from public.student_records r2
      where r2.user_id = r.user_id and r2.subject_id = r.subject_id
        and r2.state in ('pass', 'exempted')
    )
  group by r.user_id
) f on f.user_id = p.id
-- The RPS has a profile row like everyone else, but they are not their own
-- advisee. Without this they appear in their own "My Students" list, flagged
-- for having no meetings and no pillars.
where not exists (select 1 from public.admins a where a.user_id = p.id);

-- ---------------------------------------------------------------------
-- THE LEADERBOARD
--
-- This one is deliberately security_invoker = OFF: it runs with the view
-- owner's rights and so reads past RLS. That is the point — every approved
-- student needs to see every other student's engagement score. Because it
-- bypasses RLS, the column list IS the privacy boundary: name and engagement
-- only. No CGPA, no credits, no fails, no IC, no contact details.
--
-- Do not add a column here without asking whether the whole cohort may see it.
-- ---------------------------------------------------------------------
create or replace view public.leaderboard
with (security_invoker = off) as
select
  p.id                       as user_id,
  p.full_name,
  coalesce(pil.done, 0)      as pillars_done,
  coalesce(m.verified, 0)    as meetings_verified,
  coalesce(pil.done, 0) * 10 + coalesce(m.verified, 0) * 5 as points,
  coalesce(pil.done, 0) >= 7 as badge_pillars_master,
  coalesce(imp.improving, false) as badge_improving
from public.profiles p
left join (
  select user_id, count(*) as done from public.pillar_completions group by user_id
) pil on pil.user_id = p.id
left join (
  select user_id, count(*) filter (where verified) as verified
  from public.meetings group by user_id
) m on m.user_id = p.id
left join lateral (
  -- passed more subjects this semester than last
  select (
    select sp.passed_subjects from public.v_semester_passes sp
    where sp.user_id = p.id order by sp.semester_taken desc limit 1
  ) > (
    select sp.passed_subjects from public.v_semester_passes sp
    where sp.user_id = p.id order by sp.semester_taken desc offset 1 limit 1
  ) as improving
) imp on true
where p.approval_state = 'approved'
  -- the RPS is approved too, but ranking the advisor among their own advisees
  -- is nonsense; keep the board to students.
  and not exists (select 1 from public.admins a where a.user_id = p.id)
  -- Because this view runs with the owner's rights it does NOT inherit the RLS
  -- on profiles, so it has to check the caller itself. Without this line any
  -- account that merely completed signup — pending, rejected, anybody with a
  -- student address — could list every advisee by name.
  and (public.is_approved() or public.is_admin());

revoke all on public.leaderboard from anon;
grant select on public.leaderboard to authenticated;

-- Chat needs display names for people other than yourself, and profiles is
-- locked to your own row. Same pattern: bypasses RLS, exposes name only.
create or replace view public.member_names
with (security_invoker = off) as
-- avatar_path is deliberately absent: avatars live in a private bucket that
-- only the owner and the RPS may read, so chat shows initials instead.
-- Unlike the leaderboard this DOES include the RPS, otherwise their own chat
-- messages and announcements would show up with no name against them.
select p.id as user_id, p.full_name
from public.profiles p
where p.approval_state = 'approved'
  -- same reasoning as the leaderboard: owner's rights, so check the caller.
  and (public.is_approved() or public.is_admin());

revoke all on public.member_names from anon;
grant select on public.member_names to authenticated;


-- ===== 05_storage.sql ================================================

-- =====================================================================
-- myRPS — 05_storage.sql   (run FIFTH)
-- Profile photos. The bucket is PRIVATE on purpose: a public bucket means
-- every student's passport photo is fetchable by URL forever, by anyone.
-- The app reads them with short-lived signed URLs instead.
-- =====================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', false, 524288, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update
  set public = false,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;
-- 524288 bytes = 512 KB. The app also downscales to 512px before upload, so
-- 40 students cost well under 20 MB of the free tier's 1 GB.

-- Objects are stored at  <user-uuid>/avatar.jpg  — the first path segment is
-- the owner, which is what these policies check.
drop policy if exists "avatar read own" on storage.objects;
create policy "avatar read own" on storage.objects for select
  to authenticated
  using (
    bucket_id = 'avatars'
    and ((storage.foldername(name))[1] = auth.uid()::text or public.is_admin())
  );

drop policy if exists "avatar insert own" on storage.objects;
create policy "avatar insert own" on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "avatar update own" on storage.objects;
create policy "avatar update own" on storage.objects for update
  to authenticated
  using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "avatar delete own" on storage.objects;
create policy "avatar delete own" on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'avatars'
    and ((storage.foldername(name))[1] = auth.uid()::text or public.is_admin())
  );


-- ===== 06_seed.sql ===================================================

-- =====================================================================
-- myRPS — 06_seed.sql   (run SIXTH)
-- Grade scale, settings, and the UR6523007 curriculum for two intakes.
--
-- Credits and categories come straight from the printed structure and add up
-- exactly: 106 core + 6 elective + 12 common core + 14 university + 2
-- co-curriculum = 140.
--
-- planned_semester is RECONSTRUCTED from the grid. It reproduces the printed
-- per-semester totals (19/19/19/19/17/20/15/12) exactly, but a few individual
-- placements are inferred — check them against the academic guide book and fix
-- any you disagree with in Admin → Curriculum. Nothing else depends on it.
-- =====================================================================

-- ---------- grade scale (UniMAP scale, per the RPS Panduan) -----------------
insert into public.grade_scale (grade, points, is_pass, sort_order) values
  ('A', 4.00, true, 1), ('A-', 3.75, true, 2), ('B+', 3.50, true, 3),
  ('B', 3.00, true, 4), ('B-', 2.75, true, 5), ('C+', 2.50, true, 6),
  ('C', 2.00, true, 7), ('C-', 1.75, false, 8), ('D+', 1.50, false, 9),
  ('D', 1.00, false, 10), ('D-', 0.75, false, 11), ('F', 0.00, false, 12)
on conflict (grade) do update set points = excluded.points, is_pass = excluded.is_pass;
-- NOTE: B+ = 3.50 is inferred — the Panduan's table omits it, but every other
-- '+' grade is its base + 0.50. Correct it here if your faculty uses 3.25.
-- C- and below are non-passing for a core course under the UniMAP rules; adjust
-- is_pass if your programme differs.

-- ---------- settings ---------------------------------------------------------
insert into public.app_settings (key, value) values
  ('allowed_email_domain', 'studentmail.unimap.edu.my'),
  ('bootstrap_admin_email', 'CHANGE-ME@unimap.edu.my'),
  ('rps_whatsapp', '60123456789'),
  ('rps_name', 'Ts. Dr. Mohd Zamri bin Zahir Ahmad'),
  ('consent_version', '2025-v1')
on conflict (key) do nothing;
-- ^ Set bootstrap_admin_email to YOUR staff email BEFORE you register, or you
--   will not become the admin. See SETUP.md step 6.

-- ---------- credits required per block --------------------------------------
insert into public.curriculum_requirements (programme_code, intake_year, category, required_credits) values
  ('UR6523007','2025','core',106), ('UR6523007','2025','elective',6),
  ('UR6523007','2025','common_core',12), ('UR6523007','2025','university',14),
  ('UR6523007','2025','cocurriculum',2), ('UR6523007','2025','audit',0),
  ('UR6523007','2022','core',106), ('UR6523007','2022','elective',6),
  ('UR6523007','2022','common_core',12), ('UR6523007','2022','university',14),
  ('UR6523007','2022','cocurriculum',2), ('UR6523007','2022','audit',0)
on conflict (programme_code, intake_year, category) do update
  set required_credits = excluded.required_credits;

-- ---------- the courses ------------------------------------------------------
insert into public.curriculum_subjects
  (programme_code, intake_year, code, name_en, name_ms, credit, category,
   planned_semester, is_graded, counts_to_total)
values
  ('UR6523007','2025','NMK10103','Electric Circuit',null,3,'core',1,true,true),
  ('UR6523007','2025','NMK10203','Engineering Science',null,3,'core',1,true,true),
  ('UR6523007','2025','NMK10403','Digital Electronics',null,3,'core',1,true,true),
  ('UR6523007','2025','NMK11103','Electronic Engineering Skills',null,3,'core',1,true,true),
  ('UR6523007','2025','NMK12003','Engineering Materials',null,3,'core',1,true,true),
  ('UR6523007','2025','NMK10503','Electrical Engineering Technology',null,3,'core',2,true,true),
  ('UR6523007','2025','NMK10603','C Programming',null,3,'core',2,true,true),
  ('UR6523007','2025','NMK10702','Writing in Engineering Technology',null,2,'core',2,true,true),
  ('UR6523007','2025','NMK10803','Digital Systems',null,3,'core',2,true,true),
  ('UR6523007','2025','NMK34403','Engineering Technology Management',null,3,'core',2,true,true),
  ('UR6523007','2025','NMK20103','Microprocessor',null,3,'core',3,true,true),
  ('UR6523007','2025','NMK20203','Analog Electronic I',null,3,'core',3,true,true),
  ('UR6523007','2025','NMK20503','Signals and Systems',null,3,'core',3,true,true),
  ('UR6523007','2025','NMK20703','Object-Oriented Programming',null,3,'core',3,true,true),
  ('UR6523007','2025','NMK20603','Computer Architecture',null,3,'core',4,true,true),
  ('UR6523007','2025','NMK21103','Electromagnetic Theory',null,3,'core',4,true,true),
  ('UR6523007','2025','NMK21303','Analog Electronic II',null,3,'core',4,true,true),
  ('UR6523007','2025','NMK22003','Integrated Circuit Design',null,3,'core',4,true,true),
  ('UR6523007','2025','NMK30103','Communication Systems',null,3,'core',5,true,true),
  ('UR6523007','2025','NMK32003','Power Electronics',null,3,'core',5,true,true),
  ('UR6523007','2025','NMK32103','Digital Integrated Circuit Design',null,3,'core',5,true,true),
  ('UR6523007','2025','NMK32203','Microcontroller',null,3,'core',5,true,true),
  ('UR6523007','2025','NMK32303','Verification on Chip',null,3,'core',5,true,true),
  ('UR6523007','2025','NMK30004','Final Year Project 1',null,4,'core',6,true,true),
  ('UR6523007','2025','NMK31003','Digital Signal Processing',null,3,'core',6,true,true),
  ('UR6523007','2025','NMK31203','Modern Control System',null,3,'core',6,true,true),
  ('UR6523007','2025','NMK31704','Design Project',null,4,'core',6,true,true),
  ('UR6523007','2025','NMK44403','Engineering Technologist in Society',null,3,'core',6,true,true),
  ('UR6523007','2025','NMK40006','Final Year Project 2',null,6,'core',7,true,true),
  ('UR6523007','2025','NMK42003','Instrumentation',null,3,'core',7,true,true),
  ('UR6523007','2025','NMK40412','Industrial Training','Latihan Industri',12,'core',8,false,true),
  ('UR6523007','2025','NMK33003','Microelectronics Fabrication Technology',null,3,'elective',7,true,true),
  ('UR6523007','2025','NMK33103','Nanoelectronics',null,3,'elective',7,true,true),
  ('UR6523007','2025','NMK33203','Semiconductor Packaging',null,3,'elective',7,true,true),
  ('UR6523007','2025','NMK33303','Reliability and Failure Analysis',null,3,'elective',7,true,true),
  ('UR6523007','2025','NMK42103','Semiconductor Testing',null,3,'elective',7,true,true),
  ('UR6523007','2025','NMK42203','Analog Integrated Circuit Design',null,3,'elective',7,true,true),
  ('UR6523007','2025','NMK42403','IoT Technology',null,3,'elective',7,true,true),
  ('UR6523007','2025','NMK43103','Optoelectronic System',null,3,'elective',7,true,true),
  ('UR6523007','2025','NMK43003','MicroElectroMechanical System',null,3,'elective',7,true,true),
  ('UR6523007','2025','IMQ11103','Mathematics for Engineering Technology 1','Matematik untuk Teknologi Kejuruteraan 1',3,'common_core',1,true,true),
  ('UR6523007','2025','IMQ11203','Mathematics for Engineering Technology 2','Matematik untuk Teknologi Kejuruteraan 2',3,'common_core',2,true,true),
  ('UR6523007','2025','IMQ21303','Mathematics for Engineering Technology 3','Matematik untuk Teknologi Kejuruteraan 3',3,'common_core',3,true,true),
  ('UR6523007','2025','IMQ27303','Statistics for Engineering Technology','Statistik untuk Teknologi Kejuruteraan',3,'common_core',4,true,true),
  ('UR6523007','2025','SMB41002','University Malay Language','Bahasa Melayu Universiti',2,'university',2,true,true),
  ('UR6523007','2025','SMB20102','English for General Communication','Bahasa Inggeris untuk Komunikasi Am',2,'university',3,true,true),
  ('UR6523007','2025','SMU13002','Philosophy and Current Issues','Falsafah dan Isu Semasa',2,'university',3,true,true),
  ('UR6523007','2025','SMB31202','English for Technical Communication','Bahasa Inggeris untuk Komunikasi Teknikal',2,'university',4,true,true),
  ('UR6523007','2025','SMU12102','Integrity and Anti-Corruption','Integriti dan Antirasuah',2,'university',4,true,true),
  ('UR6523007','2025','SMU22402','Engineering Entrepreneurship','Keusahawanan Kejuruteraan',2,'university',5,true,true),
  ('UR6523007','2025','SMU13102','Appreciation of Ethics and Civilizations','Penghayatan Etika dan Peradaban',2,'university',6,true,true),
  ('UR6523007','2025','SMZXXX01','Co-Curriculum 1','Kokurikulum 1',1,'cocurriculum',1,true,true),
  ('UR6523007','2025','SMZXXX02','Co-Curriculum 2','Kokurikulum 2',1,'cocurriculum',6,true,true),
  ('UR6523007','2025','SMB10102','Preparatory English','Bahasa Inggeris Persediaan',2,'audit',1,true,false),
  ('UR6523007','2022','NMK10103','Electric Circuit',null,3,'core',1,true,true),
  ('UR6523007','2022','NMK10203','Engineering Science',null,3,'core',1,true,true),
  ('UR6523007','2022','NMK10403','Digital Electronics',null,3,'core',1,true,true),
  ('UR6523007','2022','NMK11103','Electronic Engineering Skills',null,3,'core',1,true,true),
  ('UR6523007','2022','NMK12003','Engineering Materials',null,3,'core',1,true,true),
  ('UR6523007','2022','NMK10503','Electrical Engineering Technology',null,3,'core',2,true,true),
  ('UR6523007','2022','NMK10603','C Programming',null,3,'core',2,true,true),
  ('UR6523007','2022','NMK10702','Writing in Engineering Technology',null,2,'core',2,true,true),
  ('UR6523007','2022','NMK10803','Digital Systems',null,3,'core',2,true,true),
  ('UR6523007','2022','NMK34403','Engineering Technology Management',null,3,'core',2,true,true),
  ('UR6523007','2022','NMK20103','Microprocessor',null,3,'core',3,true,true),
  ('UR6523007','2022','NMK20203','Analog Electronic I',null,3,'core',3,true,true),
  ('UR6523007','2022','NMK20503','Signals and Systems',null,3,'core',3,true,true),
  ('UR6523007','2022','NMK20703','Object-Oriented Programming',null,3,'core',3,true,true),
  ('UR6523007','2022','NMK20603','Computer Architecture',null,3,'core',4,true,true),
  ('UR6523007','2022','NMK21103','Electromagnetic Theory',null,3,'core',4,true,true),
  ('UR6523007','2022','NMK21303','Analog Electronic II',null,3,'core',4,true,true),
  ('UR6523007','2022','NMK22003','Integrated Circuit Design',null,3,'core',4,true,true),
  ('UR6523007','2022','NMK30103','Communication Systems',null,3,'core',5,true,true),
  ('UR6523007','2022','NMK32003','Power Electronics',null,3,'core',5,true,true),
  ('UR6523007','2022','NMK32103','Digital Integrated Circuit Design',null,3,'core',5,true,true),
  ('UR6523007','2022','NMK32203','Microcontroller',null,3,'core',5,true,true),
  ('UR6523007','2022','NMK32303','Verification on Chip',null,3,'core',5,true,true),
  ('UR6523007','2022','NMK30004','Final Year Project 1',null,4,'core',6,true,true),
  ('UR6523007','2022','NMK31003','Digital Signal Processing',null,3,'core',6,true,true),
  ('UR6523007','2022','NMK31203','Modern Control System',null,3,'core',6,true,true),
  ('UR6523007','2022','NMK31704','Design Project',null,4,'core',6,true,true),
  ('UR6523007','2022','NMK44403','Engineering Technologist in Society',null,3,'core',6,true,true),
  ('UR6523007','2022','NMK40006','Final Year Project 2',null,6,'core',7,true,true),
  ('UR6523007','2022','NMK42003','Instrumentation',null,3,'core',7,true,true),
  ('UR6523007','2022','NMK40412','Industrial Training','Latihan Industri',12,'core',8,false,true),
  ('UR6523007','2022','NMK33003','Microelectronics Fabrication Technology',null,3,'elective',7,true,true),
  ('UR6523007','2022','NMK33103','Nanoelectronics',null,3,'elective',7,true,true),
  ('UR6523007','2022','NMK33203','Semiconductor Packaging',null,3,'elective',7,true,true),
  ('UR6523007','2022','NMK33303','Reliability and Failure Analysis',null,3,'elective',7,true,true),
  ('UR6523007','2022','NMK42103','Semiconductor Testing',null,3,'elective',7,true,true),
  ('UR6523007','2022','NMK42203','Analog Integrated Circuit Design',null,3,'elective',7,true,true),
  ('UR6523007','2022','NMK42403','IoT Technology',null,3,'elective',7,true,true),
  ('UR6523007','2022','NMK43103','Optoelectronic System',null,3,'elective',7,true,true),
  ('UR6523007','2022','NMK43003','MicroElectroMechanical System',null,3,'elective',7,true,true),
  ('UR6523007','2022','SMQ11103','Mathematics for Engineering Technology 1','Matematik untuk Teknologi Kejuruteraan 1',3,'common_core',1,true,true),
  ('UR6523007','2022','SMQ11203','Mathematics for Engineering Technology 2','Matematik untuk Teknologi Kejuruteraan 2',3,'common_core',2,true,true),
  ('UR6523007','2022','SMQ21303','Mathematics for Engineering Technology 3','Matematik untuk Teknologi Kejuruteraan 3',3,'common_core',3,true,true),
  ('UR6523007','2022','SMQ27303','Statistics for Engineering Technology','Statistik untuk Teknologi Kejuruteraan',3,'common_core',4,true,true),
  ('UR6523007','2022','SMB41002','University Malay Language','Bahasa Melayu Universiti',2,'university',2,true,true),
  ('UR6523007','2022','SMB20102','English for General Communication','Bahasa Inggeris untuk Komunikasi Am',2,'university',3,true,true),
  ('UR6523007','2022','SMU13002','Philosophy and Current Issues','Falsafah dan Isu Semasa',2,'university',3,true,true),
  ('UR6523007','2022','SMB31202','English for Technical Communication','Bahasa Inggeris untuk Komunikasi Teknikal',2,'university',4,true,true),
  ('UR6523007','2022','SMU12102','Integrity and Anti-Corruption','Integriti dan Antirasuah',2,'university',4,true,true),
  ('UR6523007','2022','SMU22402','Engineering Entrepreneurship','Keusahawanan Kejuruteraan',2,'university',5,true,true),
  ('UR6523007','2022','SMU13102','Appreciation of Ethics and Civilizations','Penghayatan Etika dan Peradaban',2,'university',6,true,true),
  ('UR6523007','2022','SMZXXX01','Co-Curriculum 1','Kokurikulum 1',1,'cocurriculum',1,true,true),
  ('UR6523007','2022','SMZXXX02','Co-Curriculum 2','Kokurikulum 2',1,'cocurriculum',6,true,true),
  ('UR6523007','2022','SMB10102','Preparatory English','Bahasa Inggeris Persediaan',2,'audit',1,true,false)
on conflict (programme_code, intake_year, code) do update
  set name_en = excluded.name_en,
      name_ms = excluded.name_ms,
      credit = excluded.credit,
      category = excluded.category;

-- ---------- sanity check: should print 140 for each intake -------------------
-- select intake_year, sum(required_credits) from public.curriculum_requirements
-- group by intake_year;


-- ===== 07_realtime.sql ===============================================

-- =====================================================================
-- myRPS — 07_realtime.sql   (run LAST)
-- Turns on live updates for the chatroom. RLS still applies to realtime, so
-- an unapproved account receives nothing.
-- =====================================================================

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'chat_messages'
  ) then
    alter publication supabase_realtime add table public.chat_messages;
  end if;
end $$;

-- Optional but recommended: keep the chatroom from becoming an archive nobody
-- moderates. Deletes messages older than 120 days.
-- Schedule in Supabase → Database → Cron (pg_cron), or just run it by hand.
create or replace function public.purge_old_chat()
returns void
language sql
security definer
set search_path = public, pg_temp
as $$
  delete from public.chat_messages where created_at < now() - interval '120 days';
$$;


-- ===== 08_psychometric_items.sql =====================================

-- =====================================================================
-- myRPS — 08_psychometric_items.sql   (run EIGHTH)
-- The 70 statements of Lampiran 1, MODUL RPS 2025.
--
-- Instrument: Multiple Intelligences Test, V Chislett MSc & A Chapman
-- (2005-06), based on Howard Gardner's MI model, free from businessballs.com.
-- Used here with the lecturer's authorisation, for his own advisees only.
--
-- Each statement maps to one of seven intelligences, decoded from the shaded
-- answer grid in the module: exactly 10 statements each, so every intelligence
-- scores out of 40.
--
-- The Bahasa Melayu column is a translation for the UI. Edit any wording you'd
-- phrase differently, here or in the Supabase table editor.
-- =====================================================================

insert into public.psychometric_items (question_no, intelligence, text_en, text_ms) values
  (1, 'intrapersonal', 'I like to learn more about myself', 'Saya suka mengenali diri saya dengan lebih mendalam'),
  (2, 'musical', 'I can play a musical instrument', 'Saya boleh bermain alat muzik'),
  (3, 'kinesthetic', 'I find it easiest to solve problems when I am doing something physical', 'Saya lebih mudah menyelesaikan masalah sambil melakukan aktiviti fizikal'),
  (4, 'musical', 'I often have a song or piece of music in my head', 'Saya sering terbayang lagu atau melodi dalam fikiran'),
  (5, 'logical', 'I find budgeting and managing my money easy', 'Saya mudah menguruskan bajet dan kewangan saya'),
  (6, 'linguistic', 'I find it easy to make up stories', 'Saya mudah mereka cerita'),
  (7, 'kinesthetic', 'I have always been physically well co-ordinated', 'Saya sentiasa mempunyai koordinasi fizikal yang baik'),
  (8, 'linguistic', 'When talking to someone, I tend to listen to the words they use not just what they mean', 'Semasa berbual, saya memberi perhatian kepada pemilihan perkataan, bukan sekadar maksudnya'),
  (9, 'linguistic', 'I enjoy crosswords, word searches or other word puzzles', 'Saya suka teka silang kata atau teka-teki perkataan'),
  (10, 'logical', 'I don''t like ambiguity, I like things to be clear', 'Saya tidak suka perkara yang kabur; saya suka sesuatu yang jelas'),
  (11, 'logical', 'I enjoy logic puzzles such as ''sudoku''', 'Saya suka teka-teki logik seperti ''sudoku'''),
  (12, 'intrapersonal', 'I like to meditate', 'Saya suka bermeditasi atau bermuhasabah diri'),
  (13, 'musical', 'Music is very important to me', 'Muzik sangat penting bagi saya'),
  (14, 'linguistic', 'I am a convincing liar (if I want to be)', 'Saya boleh berbohong dengan meyakinkan (jika saya mahu)'),
  (15, 'kinesthetic', 'I play a sport or dance', 'Saya bermain sukan atau menari'),
  (16, 'intrapersonal', 'I am very interested in psychometrics (personality testing) and IQ tests', 'Saya sangat berminat dengan ujian psikometrik (ujian personaliti) dan ujian IQ'),
  (17, 'logical', 'People behaving irrationally annoy me', 'Saya rimas dengan orang yang bertindak tanpa logik'),
  (18, 'musical', 'I find that the music that appeals to me is often based on how I feel emotionally', 'Muzik yang saya minati selalunya bergantung pada perasaan saya ketika itu'),
  (19, 'interpersonal', 'I am a very social person and like being with other people', 'Saya seorang yang peramah dan suka bersama orang lain'),
  (20, 'logical', 'I like to be systematic and thorough', 'Saya suka bekerja secara sistematik dan teliti'),
  (21, 'spatial', 'I find graphs and charts easy to understand', 'Saya mudah memahami graf dan carta'),
  (22, 'kinesthetic', 'I can throw things well - darts, skimming pebbles, frisbees, etc', 'Saya pandai membaling sesuatu - dart, batu di air, frisbee dan sebagainya'),
  (23, 'linguistic', 'I find it easy to remember quotes or phrases', 'Saya mudah mengingati petikan atau ungkapan'),
  (24, 'spatial', 'I can always recognise places that I have been before, even when I was very young', 'Saya sentiasa dapat mengecam tempat yang pernah saya kunjungi, walaupun sejak kecil'),
  (25, 'musical', 'I enjoy a wide variety of musical styles', 'Saya menikmati pelbagai jenis aliran muzik'),
  (26, 'spatial', 'When I am concentrating I tend to doodle', 'Saya cenderung mencoret-coret ketika sedang menumpukan perhatian'),
  (27, 'interpersonal', 'I could manipulate people if I choose to', 'Saya boleh mempengaruhi orang lain jika saya mahu'),
  (28, 'intrapersonal', 'I can predict my feelings and behaviours in certain situations fairly accurately', 'Saya boleh menjangka perasaan dan tingkah laku saya dalam situasi tertentu dengan agak tepat'),
  (29, 'logical', 'I find mental arithmetic easy', 'Saya mudah membuat kiraan congak'),
  (30, 'musical', 'I can identify most sounds without seeing what causes them', 'Saya boleh mengecam kebanyakan bunyi tanpa melihat puncanya'),
  (31, 'linguistic', 'At school one of my favourite subjects is / was English', 'Semasa di sekolah, Bahasa Inggeris antara subjek kegemaran saya'),
  (32, 'logical', 'I like to think through a problem carefully, considering all the consequences', 'Saya suka memikirkan masalah secara mendalam dengan mengambil kira segala kesannya'),
  (33, 'linguistic', 'I enjoy debates and discussions', 'Saya suka berdebat dan berbincang'),
  (34, 'kinesthetic', 'I love adrenaline sports and scary rides', 'Saya suka sukan lasak dan permainan yang mendebarkan'),
  (35, 'intrapersonal', 'I enjoy individual sports best', 'Saya lebih suka sukan individu'),
  (36, 'interpersonal', 'I care about how those around me feel', 'Saya mengambil berat tentang perasaan orang di sekeliling saya'),
  (37, 'spatial', 'My house is full of pictures and photographs', 'Rumah saya dipenuhi gambar dan foto'),
  (38, 'kinesthetic', 'I enjoy and am good at making things - I''m good with my hands', 'Saya suka dan pandai membuat sesuatu - saya mahir menggunakan tangan'),
  (39, 'musical', 'I like having music on in the background', 'Saya suka memasang muzik sebagai latar'),
  (40, 'logical', 'I find it easy to remember telephone numbers', 'Saya mudah mengingati nombor telefon'),
  (41, 'intrapersonal', 'I set myself goals and plans for the future', 'Saya menetapkan matlamat dan merancang masa depan saya'),
  (42, 'kinesthetic', 'I am a very tactile person', 'Saya seorang yang suka menyentuh dan merasa sesuatu'),
  (43, 'interpersonal', 'I can tell easily whether someone likes me or dislikes me', 'Saya mudah mengesan sama ada seseorang menyukai saya atau tidak'),
  (44, 'spatial', 'I can easily imagine how an object would look from another perspective', 'Saya mudah membayangkan rupa sesuatu objek dari sudut yang berbeza'),
  (45, 'kinesthetic', 'I never use instructions for flat-pack furniture', 'Saya tidak pernah membaca manual semasa memasang perabot'),
  (46, 'interpersonal', 'I find it easy to talk to new people', 'Saya mudah berbual dengan orang yang baru dikenali'),
  (47, 'kinesthetic', 'To learn something new, I need to just get on and try it', 'Untuk mempelajari sesuatu yang baharu, saya perlu terus mencubanya'),
  (48, 'spatial', 'I often see clear images when I close my eyes', 'Saya kerap melihat imej yang jelas apabila memejamkan mata'),
  (49, 'logical', 'I don''t use my fingers when I count', 'Saya tidak menggunakan jari semasa mengira'),
  (50, 'linguistic', 'I often talk to myself - out loud or in my head', 'Saya kerap bercakap sendiri - secara kuat atau dalam hati'),
  (51, 'musical', 'At school I loved / love music lessons', 'Semasa di sekolah, saya suka kelas muzik'),
  (52, 'linguistic', 'When I am abroad, I find it easy to pick up the basics of another language', 'Ketika di luar negara, saya mudah mempelajari asas bahasa lain'),
  (53, 'kinesthetic', 'I find ball games easy and enjoyable', 'Saya mudah dan seronok bermain permainan bola'),
  (54, 'logical', 'My favourite subject at school is / was maths', 'Matematik adalah subjek kegemaran saya di sekolah'),
  (55, 'intrapersonal', 'I always know how I am feeling', 'Saya sentiasa tahu apa yang saya rasakan'),
  (56, 'intrapersonal', 'I am realistic about my strengths and weaknesses', 'Saya realistik tentang kekuatan dan kelemahan diri'),
  (57, 'intrapersonal', 'I keep a diary', 'Saya menulis diari'),
  (58, 'interpersonal', 'I am very aware of other people''s body language', 'Saya sangat peka terhadap bahasa badan orang lain'),
  (59, 'spatial', 'My favourite subject at school was / is art', 'Seni adalah subjek kegemaran saya di sekolah'),
  (60, 'linguistic', 'I find pleasure in reading', 'Saya seronok membaca'),
  (61, 'spatial', 'I can read a map easily', 'Saya mudah membaca peta'),
  (62, 'interpersonal', 'It upsets me to see someone cry and not be able to help', 'Saya sedih melihat seseorang menangis tanpa dapat membantu'),
  (63, 'interpersonal', 'I am good at solving disputes between others', 'Saya pandai meleraikan pertelingkahan antara orang lain'),
  (64, 'musical', 'I have always dreamed of being a musician or singer', 'Saya sentiasa bercita-cita menjadi pemuzik atau penyanyi'),
  (65, 'interpersonal', 'I prefer team sports', 'Saya lebih suka sukan berpasukan'),
  (66, 'musical', 'Singing makes me feel happy', 'Menyanyi membuatkan saya gembira'),
  (67, 'spatial', 'I never get lost when I am on my own in a new place', 'Saya tidak pernah sesat walaupun bersendirian di tempat baharu'),
  (68, 'spatial', 'If I am learning how to do something, I like to see drawings and diagrams of how it works', 'Ketika mempelajari sesuatu, saya suka melihat lukisan dan rajah cara ia berfungsi'),
  (69, 'intrapersonal', 'I am happy spending time alone', 'Saya gembira menghabiskan masa bersendirian'),
  (70, 'interpersonal', 'My friends always come to me for emotional support and advice', 'Rakan-rakan sering datang kepada saya untuk sokongan emosi dan nasihat')
on conflict (question_no) do update
  set intelligence = excluded.intelligence,
      text_en = excluded.text_en,
      text_ms = excluded.text_ms;

-- Sanity check — should return 7 rows, each with count 10:
-- select intelligence, count(*) from public.psychometric_items group by 1;


-- ============================================================================
--  Did it work? Run this afterwards in a new query. Every row should say OK.
-- ============================================================================
-- select 'tables created' as check,
--        case when count(*) >= 15 then 'OK' else 'PROBLEM' end as result
--   from pg_tables where schemaname = 'public'
-- union all
-- select 'security rules on',
--        case when count(*) = 0 then 'OK' else 'PROBLEM' end
--   from pg_class c join pg_namespace n on n.oid = c.relnamespace
--  where n.nspname = 'public' and c.relkind = 'r' and not c.relrowsecurity
-- union all
-- select 'curriculum loaded',
--        case when count(*) = 108 then 'OK' else 'PROBLEM' end
--   from public.curriculum_subjects
-- union all
-- select 'psychometric questions',
--        case when count(*) = 70 then 'OK' else 'PROBLEM' end
--   from public.psychometric_items;
